### ISSUE TITLE
Framework compatibility proble at build

### ISSUE THREAD

**Issue by frikinside** [jamesej/lyniconanc#11]
Hi, was trying to initialize the project via console commands following the instructions on the setup section of the readme.
I'm not used to .NET Core at all so I try to follow those instructions to the letter. Maybe there's something obvious that I had to do previously with .NET Core and this question is silly.

Anyway, when I tried to run this command:
`dotnet run -- --lynicon initialize-database`
or simply build:
`dotnet build`

I get the following error:
> 'LyniconANC.csproj' targets '.NETStandard,Version=v2.0; .NETFramework,Version=v4.6.1'. It cannot be referenced by a project that targets '.NETCoreApp,Version=v2.0'

After this, I tried to restore dependencies with nuget with a restore (`dotnet restore`) and try again.
Shows the same error at build.

How can I solve this issue?
Thanks in advance.

**Comment by jamesej** [comment]
Hi - this is most peculiar as it should definitely be possible for a project targetting .NETCoreApp 2.0 to target .NETStandard 2.0. In fact the test project in this repo which targets the LyniconANC library is .Net Core 2.0 and obviously works fine. Can you tell me more about your setup? Did you download the LyniconANC code from here and attach it to another project? It might be worth trying
a. Use the Nuget package instead (LyniconANC on Nuget)
b. Download the full repository and try running the LyniconANC.Release test project and see if you have issues with that.

Off the top of my head I'm thinking you might have a global install issue with .Net Core or maybe you are referencing some packages somewhere that are causing incompatibility issues.

**Comment by frikinside** [comment]
OMG I feel terrible stupid!
I didn't had installed the lastest .NETCore 2 SDK....
I installed it and now it work like a charm.

Sorry for wasting your time.
