### ISSUE TITLE
502 Error when attempting to download lyniconanc.0.0.1.zip

### ISSUE THREAD

**Issue by robearlam** [jamesej/lyniconanc#14]
Hi,

I'm attempting to follow the manual setup instructions in the wiki, but am getting a **"502 Proxy Error"** when attempting to download **https://www.lynicon.com/install/lyniconanc.0.0.1.zip**?

Thanks,
Rob

**Comment by jamesej-radical** [comment]
Hi Rob, apologies the www.lynicon.com site was down, it's up now so try again and it should work

**Comment by jamesej** [comment]
Hi, the problem was the www.lynicon.com site was down. It's up again now so apologies, if you try again it will work.
