### ISSUE TITLE
The sample SQL script refers to an invalid column

### ISSUE THREAD

**Issue by simontjell** [jamesej/lyniconanc#15]
Steps to reproduce:

1. dotnet run -- --lynicon initialize-database
2. Execute src\LyniconANC.Release\Areas\Lynicon\Admin\SQL\TilesSiteContentSetup.sql against database

Observation: 
Msg 207, Level 16, State 1, Line 3
Invalid column name 'Locale'.

**Comment by jamesej** [comment]
This is fixed, the Locale column was removed. Let us know if this causes any issues.
